[package]
name = "overcooked-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-clone = { workspace = true }
dyn-hash = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }